run:
  issues-exit-code: 1
  tests: false
  skip-files:
    - ".*_test.go$"
  skip-dirs:
    - vendor

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  cyclop:
    max-complexity: 15

linters:
  disable-all: true
  enable:
    - bodyclose
    # - unused
